import React, { useState, useEffect, useRef } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { toast } from 'react-toastify';
import { useAuth } from '../context/AuthContext';
import {
  generateFloorPlan,
  generateProjectFloorPlan,
  amendProjectFloorPlan,
  getProjectFloorPlan,
} from '../services/api';
import './FloorPlanDesigner.css';

const SCALE = 12; // pixels per foot
const ROOM_COLORS = {
  bedroom: '#E3F2FD', bathroom: '#E8F5E9', kitchen: '#FFF3E0',
  living: '#F3E5F5', drawing: '#F3E5F5', dining: '#FCE4EC',
  staircase: '#ECEFF1', porch: '#F5F5F5', garage: '#F5F5F5',
  lobby: '#FAFAFA', corridor: '#FAFAFA', store: '#EFEBE9',
  balcony: '#E0F7FA', laundry: '#F1F8E9', servant_quarter: '#FBE9E7',
};
const ROOM_BORDERS = {
  bedroom: '#90CAF9', bathroom: '#A5D6A7', kitchen: '#FFCC80',
  living: '#CE93D8', drawing: '#CE93D8', dining: '#F48FB1',
  staircase: '#B0BEC5', porch: '#BDBDBD', garage: '#BDBDBD',
  lobby: '#E0E0E0', corridor: '#E0E0E0', store: '#BCAAA4',
  balcony: '#80DEEA', laundry: '#C5E1A5', servant_quarter: '#FFAB91',
};

const FloorPlanDesigner = () => {
  const { projectId } = useParams();
  const { user } = useAuth();
  const navigate = useNavigate();

  const [plan, setPlan] = useState(null);
  const [loading, setLoading] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [amending, setAmending] = useState(false);
  const [amendment, setAmendment] = useState('');
  const [activeFloor, setActiveFloor] = useState(0);
  const [selectedRoom, setSelectedRoom] = useState(null);
  const [history, setHistory] = useState([]);
  const [version, setVersion] = useState(0);
  const [hoveredRoom, setHoveredRoom] = useState(null);

  // Standalone mode form
  const [formMode, setFormMode] = useState(!projectId);
  const [form, setForm] = useState({
    plotSize: 5, plotUnit: 'marla', floors: 1, bedrooms: 3,
    bathrooms: 2, kitchens: 1, livingRooms: 1, style: 'modern',
    specialFeatures: [], description: '',
  });

  // Load existing plan if projectId
  useEffect(() => {
    if (projectId) {
      setLoading(true);
      getProjectFloorPlan(projectId).then(res => {
        if (res.data.success && res.data.data.activePlan) {
          setPlan(res.data.data.activePlan);
          setHistory(res.data.data.history || []);
          setVersion(res.data.data.history?.length || 0);
          setFormMode(false);
        }
      }).catch(() => {}).finally(() => setLoading(false));
    }
  }, [projectId]);

  const handleGenerate = async () => {
    setGenerating(true);
    try {
      let res;
      if (projectId) {
        res = await generateProjectFloorPlan(projectId, form);
      } else {
        res = await generateFloorPlan(form);
      }
      if (res.data.success) {
        setPlan(res.data.data);
        setVersion(res.data.version || 1);
        setFormMode(false);
        setActiveFloor(0);
        setSelectedRoom(null);
        toast.success('🏠 Floor plan generated by AI!');
      }
    } catch (err) {
      toast.error(err.response?.data?.message || 'Failed to generate floor plan');
    }
    setGenerating(false);
  };

  const handleAmend = async () => {
    if (!amendment.trim()) return toast.error('Describe the change you want');
    if (!projectId) return toast.error('Save to a project first to amend');
    setAmending(true);
    try {
      const res = await amendProjectFloorPlan(projectId, amendment);
      if (res.data.success) {
        setPlan(res.data.data);
        setVersion(res.data.version);
        setAmendment('');
        toast.success('✏️ Floor plan updated!');
      }
    } catch (err) {
      toast.error(err.response?.data?.message || 'Failed to amend');
    }
    setAmending(false);
  };

  const toggleFeature = (f) => {
    setForm(prev => ({
      ...prev,
      specialFeatures: prev.specialFeatures.includes(f)
        ? prev.specialFeatures.filter(x => x !== f)
        : [...prev.specialFeatures, f],
    }));
  };

  const currentFloor = plan?.floors?.[activeFloor];

  // Render SVG floor plan
  const renderFloorPlan = () => {
    if (!plan || !currentFloor) return null;
    const pw = plan.plotDimensions.width;
    const pd = plan.plotDimensions.depth;
    const svgW = pw * SCALE + 60;
    const svgH = pd * SCALE + 80;

    return (
      <svg
        viewBox={`0 0 ${svgW} ${svgH}`}
        className="fp-svg"
        xmlns="http://www.w3.org/2000/svg"
      >
        {/* Plot boundary */}
        <rect x="30" y="40" width={pw * SCALE} height={pd * SCALE}
          fill="none" stroke="#1e3a5f" strokeWidth="3" strokeDasharray="8,4" />

        {/* Dimensions */}
        <text x={30 + (pw * SCALE) / 2} y="25" textAnchor="middle" className="fp-dim">{pw} ft</text>
        <text x="12" y={40 + (pd * SCALE) / 2} textAnchor="middle" className="fp-dim"
          transform={`rotate(-90, 12, ${40 + (pd * SCALE) / 2})`}>{pd} ft</text>

        {/* Direction indicator */}
        <text x={30 + (pw * SCALE) / 2} y={pd * SCALE + 70} textAnchor="middle" className="fp-label-sm">▲ FRONT (Road Side)</text>

        {/* Rooms */}
        {currentFloor.rooms.map((room) => {
          const rx = 30 + room.x * SCALE;
          const ry = 40 + room.y * SCALE;
          const rw = room.width * SCALE;
          const rh = room.height * SCALE;
          const isHovered = hoveredRoom === room.id;
          const isSelected = selectedRoom?.id === room.id;
          const bgColor = room.color || ROOM_COLORS[room.type] || '#F5F5F5';
          const borderColor = ROOM_BORDERS[room.type] || '#BDBDBD';

          return (
            <g key={room.id}
              onMouseEnter={() => setHoveredRoom(room.id)}
              onMouseLeave={() => setHoveredRoom(null)}
              onClick={() => setSelectedRoom(room)}
              style={{ cursor: 'pointer' }}
            >
              <rect x={rx} y={ry} width={rw} height={rh}
                fill={bgColor}
                stroke={isSelected ? '#1e3a5f' : isHovered ? '#3b82f6' : borderColor}
                strokeWidth={isSelected ? 2.5 : isHovered ? 2 : 1.2}
                rx="2"
              />
              {/* Room name */}
              <text x={rx + rw / 2} y={ry + rh / 2 - 4} textAnchor="middle" className="fp-room-name">
                {room.name.length > rw / 8 ? room.name.split(' ')[0] : room.name}
              </text>
              {/* Room dimensions */}
              <text x={rx + rw / 2} y={ry + rh / 2 + 10} textAnchor="middle" className="fp-room-dim">
                {room.width}×{room.height} ft
              </text>
              {/* Door indicator (small gap on one side) */}
              <rect x={rx + rw / 2 - 6} y={ry + rh - 1.5} width="12" height="3"
                fill={bgColor} stroke="none" />
            </g>
          );
        })}

        {/* Compass */}
        <g transform={`translate(${svgW - 35}, 55)`}>
          <circle r="14" fill="rgba(30,58,95,0.08)" stroke="#1e3a5f" strokeWidth="1" />
          <text x="0" y="-3" textAnchor="middle" className="fp-compass">N</text>
          <line x1="0" y1="2" x2="0" y2="10" stroke="#1e3a5f" strokeWidth="1.5" />
        </g>
      </svg>
    );
  };

  if (loading) return <div className="floor-plan-designer"><div className="fpd-loading"><span className="spinner"></span> Loading floor plan...</div></div>;

  return (
    <div className="floor-plan-designer">
      <div className="fpd-container">
        {/* Header */}
        <div className="fpd-header">
          <div>
            <h1>🏠 AI Floor Plan Designer</h1>
            <p>Design your dream home with AI-powered architectural layouts</p>
          </div>
          {projectId && (
            <button className="fpd-back" onClick={() => navigate(`/projects/${projectId}`)}>← Back to Project</button>
          )}
        </div>

        {/* Input Form (shown initially or when no plan) */}
        {formMode && (
          <div className="fpd-form-card">
            <h2>📐 Design Requirements</h2>
            <p className="fpd-form-desc">Tell us about your dream home — our AI will generate a professional floor plan</p>

            <div className="fpd-form-grid">
              <div className="fpd-field">
                <label>Plot Size</label>
                <div className="fpd-field-row">
                  <input type="number" value={form.plotSize}
                    onChange={e => setForm(p => ({ ...p, plotSize: parseInt(e.target.value) || 0 }))} />
                  <select value={form.plotUnit} onChange={e => setForm(p => ({ ...p, plotUnit: e.target.value }))}>
                    <option value="marla">Marla</option>
                    <option value="kanal">Kanal</option>
                    <option value="sqft">Sq Ft</option>
                  </select>
                </div>
              </div>

              <div className="fpd-field">
                <label>Floors</label>
                <div className="fpd-stepper">
                  <button onClick={() => setForm(p => ({ ...p, floors: Math.max(1, p.floors - 1) }))}>−</button>
                  <span>{form.floors}</span>
                  <button onClick={() => setForm(p => ({ ...p, floors: Math.min(4, p.floors + 1) }))}>+</button>
                </div>
              </div>

              <div className="fpd-field">
                <label>Bedrooms</label>
                <div className="fpd-stepper">
                  <button onClick={() => setForm(p => ({ ...p, bedrooms: Math.max(1, p.bedrooms - 1) }))}>−</button>
                  <span>{form.bedrooms}</span>
                  <button onClick={() => setForm(p => ({ ...p, bedrooms: Math.min(8, p.bedrooms + 1) }))}>+</button>
                </div>
              </div>

              <div className="fpd-field">
                <label>Bathrooms</label>
                <div className="fpd-stepper">
                  <button onClick={() => setForm(p => ({ ...p, bathrooms: Math.max(1, p.bathrooms - 1) }))}>−</button>
                  <span>{form.bathrooms}</span>
                  <button onClick={() => setForm(p => ({ ...p, bathrooms: Math.min(8, p.bathrooms + 1) }))}>+</button>
                </div>
              </div>

              <div className="fpd-field">
                <label>Style</label>
                <select value={form.style} onChange={e => setForm(p => ({ ...p, style: e.target.value }))}>
                  <option value="modern">Modern</option>
                  <option value="traditional">Traditional</option>
                  <option value="contemporary">Contemporary</option>
                  <option value="minimalist">Minimalist</option>
                  <option value="luxury">Luxury</option>
                </select>
              </div>
            </div>

            <div className="fpd-field fpd-field--full">
              <label>Special Features</label>
              <div className="fpd-features">
                {['Car Porch', 'Rooftop Terrace', 'Basement', 'Garden', 'Servant Quarter', 'Store Room', 'Balcony', 'Laundry Room', 'Home Office', 'Prayer Room'].map(f => (
                  <button key={f}
                    className={`fpd-feature-chip ${form.specialFeatures.includes(f.toLowerCase()) ? 'active' : ''}`}
                    onClick={() => toggleFeature(f.toLowerCase())}>
                    {f}
                  </button>
                ))}
              </div>
            </div>

            <div className="fpd-field fpd-field--full">
              <label>Additional Description (optional)</label>
              <textarea value={form.description}
                onChange={e => setForm(p => ({ ...p, description: e.target.value }))}
                placeholder="e.g., I want an open-plan living/dining area, master bedroom on ground floor, lots of natural light..."
                rows={3} />
            </div>

            <button className="fpd-generate-btn" onClick={handleGenerate} disabled={generating}>
              {generating ? (
                <><span className="spinner"></span> AI is designing your floor plan...</>
              ) : '🤖 Generate Floor Plan with AI'}
            </button>
          </div>
        )}

        {/* Floor Plan Display */}
        {plan && !formMode && (
          <>
            {/* Floor Tabs */}
            {plan.floors?.length > 1 && (
              <div className="fpd-floor-tabs">
                {plan.floors.map((f, i) => (
                  <button key={i}
                    className={`fpd-floor-tab ${activeFloor === i ? 'active' : ''}`}
                    onClick={() => { setActiveFloor(i); setSelectedRoom(null); }}>
                    {f.label || `Floor ${f.floorNumber}`}
                  </button>
                ))}
              </div>
            )}

            <div className="fpd-layout">
              {/* SVG Floor Plan */}
              <div className="fpd-plan-area">
                <div className="fpd-plan-header">
                  <h3>{currentFloor?.label || 'Ground Floor'}</h3>
                  <div className="fpd-plan-meta">
                    <span>📐 {plan.plotDimensions?.width}ft × {plan.plotDimensions?.depth}ft</span>
                    <span>📏 {plan.totalArea} sqft total</span>
                    {version > 0 && <span>v{version}</span>}
                  </div>
                </div>
                <div className="fpd-plan-svg-wrapper">
                  {renderFloorPlan()}
                </div>
              </div>

              {/* Side Panel */}
              <div className="fpd-side-panel">
                {/* Selected Room Info */}
                {selectedRoom ? (
                  <div className="fpd-room-info">
                    <h3>{selectedRoom.name}</h3>
                    <div className="fpd-room-details">
                      <div className="fpd-room-detail">
                        <span>Type</span><span>{selectedRoom.type}</span>
                      </div>
                      <div className="fpd-room-detail">
                        <span>Size</span><span>{selectedRoom.width} × {selectedRoom.height} ft</span>
                      </div>
                      <div className="fpd-room-detail">
                        <span>Area</span><span>{selectedRoom.area || selectedRoom.width * selectedRoom.height} sqft</span>
                      </div>
                      {selectedRoom.features?.length > 0 && (
                        <div className="fpd-room-detail fpd-room-detail--features">
                          <span>Features</span>
                          <div>{selectedRoom.features.map(f => <span key={f} className="fpd-room-tag">{f}</span>)}</div>
                        </div>
                      )}
                    </div>
                    <button className="fpd-room-close" onClick={() => setSelectedRoom(null)}>✕ Close</button>
                  </div>
                ) : (
                  <div className="fpd-room-info fpd-room-info--empty">
                    <p>👆 Click a room to see details</p>
                  </div>
                )}

                {/* Room Legend */}
                <div className="fpd-legend">
                  <h4>Room Legend</h4>
                  {currentFloor?.rooms?.map(room => (
                    <div key={room.id} className="fpd-legend-item"
                      onClick={() => setSelectedRoom(room)}
                      onMouseEnter={() => setHoveredRoom(room.id)}
                      onMouseLeave={() => setHoveredRoom(null)}>
                      <span className="fpd-legend-color" style={{ background: room.color || ROOM_COLORS[room.type] || '#F5F5F5' }}></span>
                      <span className="fpd-legend-name">{room.name}</span>
                      <span className="fpd-legend-area">{room.area || room.width * room.height} sqft</span>
                    </div>
                  ))}
                </div>

                {/* Design Notes */}
                {plan.designNotes?.length > 0 && (
                  <div className="fpd-notes">
                    <h4>🏗️ Design Notes</h4>
                    <ul>{plan.designNotes.map((n, i) => <li key={i}>{n}</li>)}</ul>
                  </div>
                )}

                {/* Suggestions */}
                {plan.suggestions?.length > 0 && (
                  <div className="fpd-suggestions">
                    <h4>💡 Suggestions</h4>
                    <ul>{plan.suggestions.map((s, i) => <li key={i}>{s}</li>)}</ul>
                  </div>
                )}
              </div>
            </div>

            {/* AI Amendment Bar */}
            {projectId && (
              <div className="fpd-amend-bar">
                <h3>✏️ Modify Design with AI</h3>
                <p>Describe what you'd like to change — AI will redesign accordingly</p>
                <div className="fpd-amend-input">
                  <textarea
                    value={amendment}
                    onChange={e => setAmendment(e.target.value)}
                    placeholder="e.g., Make the master bedroom bigger, add a balcony to the first floor, swap kitchen and dining room positions, add an attached bathroom to bedroom 2..."
                    rows={2}
                  />
                  <button onClick={handleAmend} disabled={amending}>
                    {amending ? <><span className="spinner"></span> Redesigning...</> : '🤖 Apply Changes'}
                  </button>
                </div>
                <div className="fpd-amend-suggestions">
                  {['Make master bedroom larger', 'Add a balcony', 'Move kitchen to the back', 'Add servant quarter', 'Open plan living+dining'].map(s => (
                    <button key={s} className="fpd-amend-chip" onClick={() => setAmendment(s)}>{s}</button>
                  ))}
                </div>
              </div>
            )}

            {/* Actions */}
            <div className="fpd-actions">
              <button className="fpd-action-btn fpd-action-btn--secondary" onClick={() => setFormMode(true)}>
                🔄 New Design
              </button>
              {!projectId && (
                <button className="fpd-action-btn fpd-action-btn--primary" onClick={() => navigate('/projects/new')}>
                  📝 Save to Project
                </button>
              )}
            </div>
          </>
        )}
      </div>
    </div>
  );
};

export default FloorPlanDesigner;
